### ISSUE TITLE
Gonna do cpp/etc?

### ISSUE THREAD

**Issue by MSGhero** [MSGhero/NG.hx#2]
Flash and html5 (I assume) have access to Newgrounds vars such as username, userId, etc.  What should be done about the cpp exports and java and stuff?  Should use of the api be restricted to flash and js?

Tracking player count, hosts, and custom events are nice in general and don't rely on being logged in.

**Comment by MintPaw** [comment]
It should likely be restricted to Flash and html5 for now, maybe later a log in can be added so you can play on Android and Ouya and such and rack achievements.

**Comment by MSGhero** [comment]
Flash + js for now, others in the future.
